Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with pd.ExcelWriter(os.path.join(output_dir, "naive_bayes_results.xlsx")) as writer:
    prior_df.to_excel(writer, sheet_name="Prior_Probability", index=False)
    mu_df.to_excel(writer, sheet_name="Mean_per_Class")
    var_df.to_excel(writer, sheet_name="Variance_per_Class")
    cm_df.to_excel(writer, sheet_name="Confusion_Matrix")
    class_report_df.to_excel(writer, sheet_name="Classification_Report")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[16], line 1[0m
[0;32m----> 1[0m [38;5;28;01mwith[39;00m [43mpd[49m[38;5;241;43m.[39;49m[43mExcelWriter[49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43moutput_dir[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mnaive_bayes_results.xlsx[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m)[49m [38;5;28;01mas[39;00m writer:
[1;32m      2[0m     prior_df[38;5;241m.[39mto_excel(writer, sheet_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mPrior_Probability[39m[38;5;124m"[39m, index[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m      3[0m     mu_df[38;5;241m.[39mto_excel(writer, sheet_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mMean_per_Class[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py:57[0m, in [0;36mOpenpyxlWriter.__init__[0;34m(self, path, engine, date_format, datetime_format, mode, storage_options, if_sheet_exists, engine_kwargs, **kwargs)[0m
[1;32m     44[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m__init__[39m(
[1;32m     45[0m     [38;5;28mself[39m,
[1;32m     46[0m     path: FilePath [38;5;241m|[39m WriteExcelBuffer [38;5;241m|[39m ExcelWriter,
[0;32m   (...)[0m
[1;32m     55[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m     56[0m     [38;5;66;03m# Use the openpyxl module as the Excel writer.[39;00m
[0;32m---> 57[0m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mopenpyxl[39;00m[38;5;21;01m.[39;00m[38;5;21;01mworkbook[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Workbook
[1;32m     59[0m     engine_kwargs [38;5;241m=[39m combine_kwargs(engine_kwargs, kwargs)
[1;32m     61[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(
[1;32m     62[0m         path,
[1;32m     63[0m         mode[38;5;241m=[39mmode,
[0;32m   (...)[0m
[1;32m     66[0m         engine_kwargs[38;5;241m=[39mengine_kwargs,
[1;32m     67[0m     )

[0;31mModuleNotFoundError[0m: No module named 'openpyxl'

